export interface SampleAnswerFull {
  id: string;
  answer_text: string;
  word_count: number;
  grade_tier: string;
  pclm_target: { P: number; C: number; L: number; M: number } | null;
  selected_poems: string[] | null;
  generation_model: string | null;
  created_at: string;
  approved: boolean;
  reviewer_notes: string | null;
  question: {
    question_text: string;
    exam_year: number | null;
    subject_key: string;
  };
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-GB", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}

function pclmLine(pclm: { P: number; C: number; L: number; M: number } | null): string {
  if (!pclm) return "N/A";
  return `P ${pclm.P} · C ${pclm.C} · L ${pclm.L} · M ${pclm.M}`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

export function toPlainText(row: SampleAnswerFull): string {
  const { question, grade_tier, pclm_target, selected_poems, answer_text, generation_model, created_at, word_count } = row;
  const year = question.exam_year ?? "Unknown year";
  const poems = selected_poems && selected_poems.length > 0 ? selected_poems.join(", ") : "N/A";
  const paragraphs = answer_text.split(/\n\n+/).join("\n\n");

  return [
    "QUESTION",
    `${year}, Higher Level Paper 2`,
    "",
    question.question_text,
    "",
    `GRADE TIER: ${grade_tier}`,
    `PCLM TARGET: ${pclmLine(pclm_target)}`,
    `SELECTED POEMS: ${poems}`,
    "",
    "ANSWER",
    "",
    paragraphs,
    "",
    "---",
    `Generated by LC Companion on ${formatDate(created_at)} · ${generation_model ?? "Claude"} · ${word_count} words`,
  ].join("\n");
}

export function toHtml(row: SampleAnswerFull): string {
  const { question, grade_tier, pclm_target, selected_poems, answer_text, generation_model, created_at, word_count } = row;
  const year = question.exam_year ?? "Unknown year";
  const poems = selected_poems && selected_poems.length > 0 ? selected_poems.join(", ") : "N/A";
  const paragraphsHtml = answer_text
    .split(/\n\n+/)
    .map((p) => `  <p>${escapeHtml(p.trim())}</p>`)
    .join("\n");

  return `<article>
  <header>
    <h2>Question</h2>
    <p><strong>${escapeHtml(String(year))}, Higher Level Paper 2</strong></p>
    <p>${escapeHtml(question.question_text)}</p>
  </header>
  <section>
    <p><strong>Grade tier:</strong> ${escapeHtml(grade_tier)}</p>
    <p><strong>PCLM target:</strong> ${escapeHtml(pclmLine(pclm_target))}</p>
    <p><strong>Selected poems:</strong> ${escapeHtml(poems)}</p>
  </section>
  <section>
    <h2>Answer</h2>
${paragraphsHtml}
  </section>
  <footer>
    <hr>
    <p><small>Generated by LC Companion on ${escapeHtml(formatDate(created_at))} · ${escapeHtml(generation_model ?? "Claude")} · ${word_count} words</small></p>
  </footer>
</article>`;
}
